### ISSUE TITLE
Replace Unlicensed with MIT License

### ISSUE THREAD

**Issue by bmg817** [PeterFidelman/CommunityConstructor#29]
Hi team,

Looking at the [OSI recommendations](https://opensource.org/licenses/category), it seems like the MIT License is the best version to use for this repository. Could you replace Unlicensed with MIT License?

**Comment by PeterFidelman** [comment]
It is Unlicense on purpose.

From the MIT-license...

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

...MIT-licensed software remains under copyright and requires attribution.  I chose the Unlicense to make it clear that I relinquish all hold on the software and put it in the public domain for anyone to use and modify however they want.
